In [1]:
# 1. Importing Pandas
# Aliasing >> short name for referencing
import pandas as pd

In [2]:
a = [1,2,3,4,5] # 1d list

In [3]:
a[2]

3

In [4]:
type(a)

list

In [5]:
b = [10, 20, 30, 40, 50, 55, 60, 65, 70, 75]
print(b)

[10, 20, 30, 40, 50, 55, 60, 65, 70, 75]

In [6]:
# 2. Creating a Series
data = pd.Series(b)
data

0    10
1    20
2    30
3    40
4    50
5    55
6    60
7    65
8    70
9    75
dtype: int64

In [7]:
data[9]

np.int64(75)

In [8]:
print(f"data\n {data}, type: {type(data)}")

data
 0    10
1    20
2    30
3    40
4    50
5    55
6    60
7    65
8    70
9    75
dtype: int64, type: <class 'pandas.Series'>

In [9]:
data[0]

np.int64(10)

In [10]:
data[6]

np.int64(60)

In [11]:
data[1:5]

1    20
2    30
3    40
4    50
dtype: int64

In [12]:
data[:5]

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
data[5:]

5    55
6    60
7    65
8    70
9    75
dtype: int64

In [14]:
data.shape # Dimensions

(10,)

In [15]:
data.size # length / number of elements

10

In [14]:
data.sum()

np.int64(475)

In [15]:
data.mean()

np.float64(47.5)

In [17]:
data.max()

np.int64(75)

In [18]:
data.std()

np.float64(21.88987589427283)

In [19]:
a = [[1,2,3], [4,5,6], [7,8,9], [6,5,4]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [6, 5, 4]]

In [20]:
a[0]

[1, 2, 3]

In [21]:
a[1][2] # 2d list [row][col]

6

In [16]:
a[2] # a[row]

3

In [17]:
a = [[1,2,3], [4,5,6], [7,8,9], [6,5,4]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [6, 5, 4]]

In [21]:
# 3. Creating a DataFrame using lists

a = [[1,2,3], [4,5,6], [7,8,9], [6,5,4]]
df = pd.DataFrame(a)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
3  6  5  4

In [22]:
df.columns = ["col1", "col2", "col3"]
df

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9
3     6     5     4

In [23]:
type(df["col1"])

pandas.Series

In [24]:
df["col1"]

0    1
1    4
2    7
3    6
Name: col1, dtype: int64

In [25]:
df["col1"].mean()

np.float64(4.5)

In [26]:
df["col1"].max()

np.int64(7)

In [27]:
df.shape

(4, 3)

In [28]:
df.size

12

In [29]:
df['col2'] # values in col2

0    2
1    5
2    8
3    5
Name: col2, dtype: int64

In [30]:
print(type(df['col2']))
df['col2']

<class 'pandas.Series'>

0    2
1    5
2    8
3    5
Name: col2, dtype: int64

In [31]:
# 3. Creating a DataFrame
data = {
    'Name': ['Ali', "Alice", 'Bob', 'Charlie', "Ahmad", "Olex", "Camel", "Barbie"],
    'Age': [25, 30, 35, 22, 33, 44, 55, 66],
    'City': ['LHR', 'KHI', "ISB", "MLT", "KHI", " ", "ISB", "KHI"],
    "Score": [66, 77, 88, 99, 55, 77, 66, 88]
}
df = pd.DataFrame(data)
df

      Name  Age City  Score
0      Ali   25  LHR     66
1    Alice   30  KHI     77
2      Bob   35  ISB     88
3  Charlie   22  MLT     99
4    Ahmad   33  KHI     55
5     Olex   44          77
6    Camel   55  ISB     66
7   Barbie   66  KHI     88

In [32]:
data

{'Name': ['Ali',
  'Alice',
  'Bob',
  'Charlie',
  'Ahmad',
  'Olex',
  'Camel',
  'Barbie'],
 'Age': [25, 30, 35, 22, 33, 44, 55, 66],
 'City': ['LHR', 'KHI', 'ISB', 'MLT', 'KHI', ' ', 'ISB', 'KHI'],
 'Score': [66, 77, 88, 99, 55, 77, 66, 88]}

In [33]:
df.shape

(8, 4)

In [34]:
df.size

32

In [35]:
# 4. Inspecting Data
df.head()

      Name  Age City  Score
0      Ali   25  LHR     66
1    Alice   30  KHI     77
2      Bob   35  ISB     88
3  Charlie   22  MLT     99
4    Ahmad   33  KHI     55

In [36]:
df.head(10)

      Name  Age City  Score
0      Ali   25  LHR     66
1    Alice   30  KHI     77
2      Bob   35  ISB     88
3  Charlie   22  MLT     99
4    Ahmad   33  KHI     55
5     Olex   44          77
6    Camel   55  ISB     66
7   Barbie   66  KHI     88

In [37]:
df.tail(6)

      Name  Age City  Score
2      Bob   35  ISB     88
3  Charlie   22  MLT     99
4    Ahmad   33  KHI     55
5     Olex   44          77
6    Camel   55  ISB     66
7   Barbie   66  KHI     88

In [38]:
df.shape

(8, 4)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Age     8 non-null      int64
 2   City    8 non-null      str
 3   Score   8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

In [40]:
df.describe()

             Age      Score
count   8.000000   8.000000
mean   38.750000  77.000000
std    15.247951  14.402381
min    22.000000  55.000000
25%    28.750000  66.000000
50%    34.000000  77.000000
75%    46.750000  88.000000
max    66.000000  99.000000

In [41]:
df.columns # Attribute

Index(['Name', 'Age', 'City', 'Score'], dtype='str')

In [42]:
df.dtypes

Name       str
Age      int64
City       str
Score    int64
dtype: object

In [43]:
# 5. Selecting Data
df['Name']

0        Ali
1      Alice
2        Bob
3    Charlie
4      Ahmad
5       Olex
6      Camel
7     Barbie
Name: Name, dtype: str

In [44]:
df[['Name', 'Age']] # selecting 2 cols by name

      Name  Age
0      Ali   25
1    Alice   30
2      Bob   35
3  Charlie   22
4    Ahmad   33
5     Olex   44
6    Camel   55
7   Barbie   66

In [45]:
df.loc[0]

Name     Ali
Age       25
City     LHR
Score     66
Name: 0, dtype: object

In [46]:
df.iloc[1:3] # 1st 2 rows data

    Name  Age City  Score
1  Alice   30  KHI     77
2    Bob   35  ISB     88

In [47]:
df.iloc[1:3, 1:4] # 1st rows : 1st 3 cols

   Age City  Score
1   30  KHI     77
2   35  ISB     88

In [48]:
df.loc[1:3,"Age"]

1    30
2    35
3    22
Name: Age, dtype: int64

In [49]:
df.loc[1:3,["Age", "Name"]]

   Age     Name
1   30    Alice
2   35      Bob
3   22  Charlie

In [50]:
# 3. Creating a DataFrame using lists

a = [[1,2,3], [4,5,6], [7,8,9], [6,5,4]]
df = pd.DataFrame(a)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
3  6  5  4

In [51]:
print(df.columns)

RangeIndex(start=0, stop=3, step=1)

In [52]:
df.columns = ["Col_1", "Col_2", "Col_3"]
df

   Col_1  Col_2  Col_3
0      1      2      3
1      4      5      6
2      7      8      9
3      6      5      4

In [56]:
# 6. Filtering Data
df[df['Score'] > 50]

KeyError: 'score'

In [54]:
df[(df['Age'] > 40) & (df['City'] == 'ISB')]

KeyError: 'Age'

In [4]:
# 7. Modifying Data
df['Salary'] = df["Score"] * 1000
# df['Age'] = df['Age'] + 1
df

      Name  Age City  Score  Salary
0      Ali   25  LHR     66   66000
1    Alice   30  KHI     77   77000
2      Bob   35  ISB     88   88000
3  Charlie   22  MLT     99   99000
4    Ahmad   33  KHI     55   55000
5     Olex   44  LHR     77   77000
6    Camel   55  ISB     66   66000
7   Barbie   66  KHI     88   88000

In [7]:
df2 = df.rename(columns={'Age': 'Years'})
df2

      Name  Years City  Score  Salary
0      Ali     25  LHR     66   66000
1    Alice     30  KHI     77   77000
2      Bob     35  ISB     88   88000
3  Charlie     22  MLT     99   99000
4    Ahmad     33  KHI     55   55000
5     Olex     44  LHR     77   77000
6    Camel     55  ISB     66   66000
7   Barbie     66  KHI     88   88000

In [8]:
df

      Name  Age City  Score  Salary
0      Ali   25  LHR     66   66000
1    Alice   30  KHI     77   77000
2      Bob   35  ISB     88   88000
3  Charlie   22  MLT     99   99000
4    Ahmad   33  KHI     55   55000
5     Olex   44  LHR     77   77000
6    Camel   55  ISB     66   66000
7   Barbie   66  KHI     88   88000

In [9]:
df.rename(columns={'Age': 'Years'}, inplace=True) # CHanges orignal dataframe
df

      Name  Years City  Score  Salary
0      Ali     25  LHR     66   66000
1    Alice     30  KHI     77   77000
2      Bob     35  ISB     88   88000
3  Charlie     22  MLT     99   99000
4    Ahmad     33  KHI     55   55000
5     Olex     44  LHR     77   77000
6    Camel     55  ISB     66   66000
7   Barbie     66  KHI     88   88000

In [10]:
# 8. Handling Missing Data
df_missing = df.copy()
df_missing

      Name  Years City  Score  Salary
0      Ali     25  LHR     66   66000
1    Alice     30  KHI     77   77000
2      Bob     35  ISB     88   88000
3  Charlie     22  MLT     99   99000
4    Ahmad     33  KHI     55   55000
5     Olex     44  LHR     77   77000
6    Camel     55  ISB     66   66000
7   Barbie     66  KHI     88   88000

In [12]:
df_missing.isnull().sum()

Name      0
Years     0
City      0
Score     0
Salary    0
dtype: int64

In [14]:
df_missing.loc[1:5, 'Salary'] = None
df_missing

      Name  Years City  Score   Salary
0      Ali     25  LHR     66  66000.0
1    Alice     30  KHI     77      NaN
2      Bob     35  ISB     88      NaN
3  Charlie     22  MLT     99      NaN
4    Ahmad     33  KHI     55      NaN
5     Olex     44  LHR     77      NaN
6    Camel     55  ISB     66  66000.0
7   Barbie     66  KHI     88  88000.0

In [15]:
df_missing.isnull()

    Name  Years   City  Score  Salary
0  False  False  False  False   False
1  False  False  False  False    True
2  False  False  False  False    True
3  False  False  False  False    True
4  False  False  False  False    True
5  False  False  False  False    True
6  False  False  False  False   False
7  False  False  False  False   False

In [16]:
df_missing.isnull().sum()

Name      0
Years     0
City      0
Score     0
Salary    5
dtype: int64

In [17]:
df3 = df_missing.fillna(0)
df3

      Name  Years City  Score   Salary
0      Ali     25  LHR     66  66000.0
1    Alice     30  KHI     77      0.0
2      Bob     35  ISB     88      0.0
3  Charlie     22  MLT     99      0.0
4    Ahmad     33  KHI     55      0.0
5     Olex     44  LHR     77      0.0
6    Camel     55  ISB     66  66000.0
7   Barbie     66  KHI     88  88000.0

In [18]:
df_missing

      Name  Years City  Score   Salary
0      Ali     25  LHR     66  66000.0
1    Alice     30  KHI     77      NaN
2      Bob     35  ISB     88      NaN
3  Charlie     22  MLT     99      NaN
4    Ahmad     33  KHI     55      NaN
5     Olex     44  LHR     77      NaN
6    Camel     55  ISB     66  66000.0
7   Barbie     66  KHI     88  88000.0

In [19]:
df_missing.dropna()

     Name  Years City  Score   Salary
0     Ali     25  LHR     66  66000.0
6   Camel     55  ISB     66  66000.0
7  Barbie     66  KHI     88  88000.0

In [20]:
# 9. Sorting Data
df.sort_values('Salary')

      Name  Years City  Score  Salary
4    Ahmad     33  KHI     55   55000
0      Ali     25  LHR     66   66000
6    Camel     55  ISB     66   66000
1    Alice     30  KHI     77   77000
5     Olex     44  LHR     77   77000
2      Bob     35  ISB     88   88000
7   Barbie     66  KHI     88   88000
3  Charlie     22  MLT     99   99000

In [21]:
df.sort_values('Salary', ascending=False)

      Name  Years City  Score  Salary
3  Charlie     22  MLT     99   99000
2      Bob     35  ISB     88   88000
7   Barbie     66  KHI     88   88000
1    Alice     30  KHI     77   77000
5     Olex     44  LHR     77   77000
0      Ali     25  LHR     66   66000
6    Camel     55  ISB     66   66000
4    Ahmad     33  KHI     55   55000

In [39]:
# 10. Grouping and Aggregation
df.groupby('City')['Salary'].mean()

City
ISB    77000.000000
KHI    73333.333333
LHR    71500.000000
MLT    99000.000000
Name: Salary, dtype: float64

In [42]:
df.groupby('City')['Salary'].mean()

City
ISB    77000.000000
KHI    73333.333333
LHR    71500.000000
MLT    99000.000000
Name: Salary, dtype: float64

In [22]:
df.groupby('City').size() 
# Groups the DataFrame by the unique values in the City column.
# Returns the number of rows in each group

City
ISB    2
KHI    3
LHR    2
MLT    1
dtype: int64

In [23]:
# 11. Saving Data
df.to_csv('output.csv', index=False)
# df.to_excel('output.xlsx', index=False)

In [24]:
df33 = pd.read_csv("output_2.csv")
df33

      Name  Years City  Score  Salary
0      Ali     25  LHR     66   66000
1    Alice     30  KHI     77   77000
2      Bob     35  ISB     88   88000
3  Charlie     22  MLT     99   99000
4    Ahmad     33  KHI     55   55000
5     Olex     44  LHR     77   77000
6    Camel     55  ISB     66   66000
7   Barbie     66  KHI     88   88000

In [46]:
df33.describe()

           Years      Score        Salary
count   8.000000   8.000000      8.000000
mean   38.750000  77.000000  77000.000000
std    15.247951  14.402381  14402.380756
min    22.000000  55.000000  55000.000000
25%    28.750000  66.000000  66000.000000
50%    34.000000  77.000000  77000.000000
75%    46.750000  88.000000  88000.000000
max    66.000000  99.000000  99000.000000

In [19]:
# 12. Merging DataFrames
df1 = pd.DataFrame({'ID': [1, 2], 'Name': ['Ali', 'Sara']})
df2 = pd.DataFrame({'ID': [1, 2], 'Score': [85, 90]})
merged = pd.merge(df1, df2, on='ID')
merged

   ID  Name  Score
0   1   Ali     85
1   2  Sara     90

# Task

- Find Avg_Marks for each student and each subject? Given Data:

```
data = {
    "roll No": [221,222,223,224,225],
    "subj1":[50,60,70,80,90],
    "subj2":[90,80,70,60,50],
    "subj3":[95,85,75,65,55]
}
```

In [2]:
import pandas as pd
data = {
    "roll No": [221,222,223,224,225],
    "subj1":[50,60,70,80,90],
    "subj2":[90,80,70,60,50],
    "subj3":[95,85,75,65,55]
}
df= pd.DataFrame(data)
print(df)

   roll No  subj1  subj2  subj3
0      221     50     90     95
1      222     60     80     85
2      223     70     70     75
3      224     80     60     65
4      225     90     50     55

In [3]:
df.describe()

          roll No      subj1      subj2      subj3
count    5.000000   5.000000   5.000000   5.000000
mean   223.000000  70.000000  70.000000  75.000000
std      1.581139  15.811388  15.811388  15.811388
min    221.000000  50.000000  50.000000  55.000000
25%    222.000000  60.000000  60.000000  65.000000
50%    223.000000  70.000000  70.000000  75.000000
75%    224.000000  80.000000  80.000000  85.000000
max    225.000000  90.000000  90.000000  95.000000

In [4]:
df["subj1"].mean()

np.float64(70.0)

In [5]:
df["avg_marks"] = (df['subj1'] + df['subj2'] + df['subj3'])/3
df

   roll No  subj1  subj2  subj3  avg_marks
0      221     50     90     95  78.333333
1      222     60     80     85  75.000000
2      223     70     70     75  71.666667
3      224     80     60     65  68.333333
4      225     90     50     55  65.000000

In [13]:
df[['subj1', 'subj2', 'subj3']] # Selected 3 Subject Cols

   subj1  subj2  subj3
0     50     90     95
1     60     80     85
2     70     70     75
3     80     60     65
4     90     50     55

In [10]:
df['Avg2'] = df[['subj1', 'subj2', 'subj3']].mean(axis=1) # axis = 1 >> row-wise avg
df

   roll No  subj1  subj2  subj3  avg_marks       Avg2
0      221     50     90     95  78.333333  78.333333
1      222     60     80     85  75.000000  75.000000
2      223     70     70     75  71.666667  71.666667
3      224     80     60     65  68.333333  68.333333
4      225     90     50     55  65.000000  65.000000